- name: Installing stow
  homebrew:
    name: stow
    state: present
  tags:
    - dotfiles
    - stow
- name: Cloning dotfiles-awesome
  ansible.builtin.git:
    repo: "git@github.com:zhongjis/dotfiles-awesome.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles-awesome"
    update: true
    version: main
  tags:
    - dotfiles
- name: Stow files for Mac
  shell: cd $HOME/dotfiles-awesome && ./darwin.sh
  when: ansible_os_family == "Darwin"
  tags:
    - stow
    - dotfiles
- name: Stow files for Debian
  shell: cd $HOME/dotfiles-awesome && ./ubuntu.sh
  when: ansible_os_family == "Debian"
  tags:
    - stow
    - dotfiles
