- name: Installing stow
  homebrew:
    name: stow
    state: present
  tags:
    - dotfiles
    - stow
- name: Cloning dotfiles-awesome
  ansible.builtin.git:
    repo: "git@github.com:zhongjis/dotfiles-awesome.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles-awesome"
    update: true
    version: main
  tags:
    - dotfiles
- name: Stow files
  shell: cd $HOME/dotfiles-awesome && sudo ./setup.sh
  tags:
    - stow
    - dotfiles
