- name: Ensure .ssh directory exists.
  file:
    dest: "{{ ssh_dest }}"
    mode: 0700
    state: directory
  tags:
    - ssh
    - dotfiles
- name: Install ssh key
  copy:
    src: "{{ ssh_source }}"
    dest: "{{ dest_key }}"
    mode: 0600
  tags:
    - ssh
    - dotfiles
- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  tags:
    - ssh
    - dotfiles
