- name: Check if OMZ is already installed
  stat:
    path: /Users/zshen/.oh-my-zsh
  register: omz_check
  tags: 
    - zsh
    - omz
- name: Install Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  when: not omz_check.stat.exists
  tags:
    - zsh
    - omz
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  when: not omz_check.stat.exists
  tags:
    - zsh
    - plugins
- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  when: not omz_check.stat.exists
  tags:
    - zsh
    - plugins
- name: Install exa
  homebrew:
    name: exa
    state: present
  tags:
    - zsh
    - plugins
